export const RectangleHighlightBtnCls = [
  'touch-manipulation',
  'py-3',
  'px-4',
  'h-[36px]',
  'inline-flex',
  'items-center',
  'gap-x-2',
  'text-sm',
  'font-medium',
  'rounded-2xl',
  'border',
  'border-gray-200',
  'bg-white',
  'text-gray-800',
  'shadow-sm',
  'hover:bg-gray-50',
  'focus:outline-none',
  'focus:bg-gray-50',
  'disabled:opacity-50',
  'disabled:pointer-events-none',
  'dark:bg-neutral-800',
  'dark:border-neutral-700',
  'dark:text-white',
  'dark:hover:bg-neutral-700',
  'dark:focus:bg-neutral-700',
]

export const RectangleHighlightBtnIconSvgCls = ['shrink-0', 'size-4']
export const RectangleHighlightBtnTextCls = ['text-[10px]', 'leading-tight']
