export const ResetRedoUndoBtnCls = [
  'touch-manipulation',
  'py-2',
  'px-3',
  'flex',
  'shrink-0',
  'justify-center',
  'items-center',
  'gap-2',
  'size-[36px]',
  'text-sm',
  'font-medium',
  'rounded-2xl',
  'border',
  'border-gray-200',
  'bg-white',
  'shadow-sm',
  'hover:bg-gray-50',
  'focus:outline-none',
  'focus:bg-gray-50',
  'disabled:opacity-50',
  'disabled:pointer-events-none',
  'dark:bg-neutral-800',
  'dark:border-neutral-700',
  'dark:text-white',
  'dark:hover:bg-neutral-700',
  'dark:focus:bg-neutral-700',
]

export const ResetRedoUndoBtnIconSvgCls = ['shrink-0', 'size-4']
